= Introduction

Software testing has become an indispensable practice in modern software engineering, ensuring that systems meet quality standards and function correctly under various conditions @pressman2014. The complexity of contemporary web applications, which integrate multiple technologies, databases, and external services, demands comprehensive testing strategies that go beyond simple unit tests @myers2011. As systems grow in complexity, the need for systematic testing approaches that cover all levels becomes increasingly critical @iso29119.

The event management and ticketing domain presents unique challenges for software testing. Systems like alf.io must handle concurrent reservations, process payments through multiple gateways, manage digital ticket generation, and provide real-time check-in capabilities @alfio2014. These requirements create complex interactions between components that can only be validated through rigorous testing at multiple levels. The financial nature of ticketing transactions adds another layer of complexity, as errors can result in revenue loss and damaged reputation.

This paper presents the implementation of a comprehensive testing strategy for alf.io, an open-source event ticketing platform. The project involved designing and executing tests across four distinct levels: unit, integration, system, and acceptance testing @cohn2004. Each level addressed specific quality attributes and used specialized tools and methodologies to validate different aspects of the system's behavior.

The testing implementation covered the entire technology stack of alf.io, including the Java/Spring Boot backend @springboot2024, Angular public frontend, and Lit-based administration interface. The strategy incorporated automated testing through GitHub Actions CI/CD pipelines @githubactions2024, performance testing with K6 @k6performance2024, fuzzing with Jazzer @jazzer2023, and static analysis with SonarQube @sonarqube2024. This multi-layered approach ensured comprehensive coverage of both functional and non-functional requirements.

The results demonstrate the effectiveness of the implemented testing strategy, achieving 100% pass rates across unit, integration, and end-to-end tests, with an aggregated code coverage of 85.76% @coverage2015. The project also identified and documented defects, validated API contracts, and established reproducible testing processes through automated pipelines @cicd2016. This work provides a practical reference for implementing comprehensive testing strategies in similar open-source web applications @ossquality2007.
