= Conclusión <sec:conclusion>

La estrategia integral de pruebas implementada para alf.io demostró la efectividad de un enfoque multicapa para el aseguramiento de calidad de software. El proyecto alcanzó tasas de aprobación del 100% en pruebas unitarias, de integración y de aceptación, manteniendo una cobertura de código agregada del 85.76%. Estos resultados validaron la metodología de pruebas y confirmaron la corrección funcional del sistema.

La fase de pruebas unitarias estableció una base sólida validando componentes individuales de forma aislada. La combinación de JUnit 5 con Mockito para backend y Vitest para frontend proporcionó cobertura integral de lógica de negocio, controladores API y componentes de interfaz de usuario. La ejecución automatizada a través de GitHub Actions aseguró resultados consistentes de pruebas y retroalimentación rápida para los desarrolladores.

Las pruebas de integración confirmaron que los componentes del sistema interactuaban correctamente con dependencias reales. El uso de Testcontainers para instancias efímeras de PostgreSQL, Stripe Mock para pruebas de pago y Playwright para automatización de navegadores proporcionó validación realista del stack completo del sistema. La validación de contratos de API a través de OpenAPI y Redoc aseguró la estabilidad de la API entre versiones.

La fase de pruebas funcionales, conducida mediante ejecución manual de más de 120 casos de prueba, validó la funcionalidad orientada al usuario en 15 módulos. Estas pruebas identificaron defectos que las pruebas automatizadas no pudieron detectar, como inconsistencias en el comportamiento de la interfaz de usuario y casos extremos en interacciones de usuario. La aplicación sistemática de técnicas de caja negra aseguró cobertura integral de requisitos funcionales.

Las pruebas de sistema abordaron requisitos no funcionales mediante pruebas de rendimiento con K6, fuzzing con Jazzer y análisis estático con SonarQube. Si bien las pruebas de rendimiento identificaron un problema de escalabilidad bajo carga extrema, el sistema demostró degradación elegante. El fuzzing confirmó el manejo robusto de entradas inválidas con cero crashes críticos, y SonarQube identificó áreas de mejora en calidad de código con un ratio de deuda técnica aceptable del 0.5%.

La implementación estableció procesos de prueba reproducibles mediante pipelines CI/CD automatizados, documentación integral siguiendo estándares ISO/IEC/IEEE 29119 y seguimiento sistemático de defectos. El proyecto demostró que las estrategias de pruebas integrales, cuando se planifican y ejecutan adecuadamente, pueden mejorar significativamente la calidad del software mientras proporcionan retroalimentación valiosa para equipos de desarrollo trabajando en aplicaciones web complejas.
