= Introducción

Las pruebas de software se han convertido en una práctica indispensable en la ingeniería de software moderna, garantizando que los sistemas cumplan con estándares de calidad y funcionen correctamente bajo diversas condiciones @pressman2014. La complejidad de las aplicaciones web contemporáneas, que integran múltiples tecnologías, bases de datos y servicios externos, demanda estrategias de prueba integrales que trasciendan las pruebas unitarias básicas @myers2011. A medida que los sistemas crecen en complejidad, la necesidad de enfoques sistemáticos de prueba que cubran todos los niveles se vuelve cada vez más crítica @iso29119.

El dominio de gestión de eventos y venta de entradas presenta desafíos únicos para las pruebas de software. Sistemas como alf.io deben gestionar reservas concurrentes, procesar pagos a través de múltiples pasarelas, administrar la generación de entradas digitales y proporcionar funcionalidades de check-in en tiempo real @alfio2014. Estos requisitos crean interacciones complejas entre componentes que solo pueden validarse mediante pruebas rigurosas en múltiples niveles. La naturaleza financiera de las transacciones de boletos añade otra capa de complejidad, dado que los errores pueden resultar en pérdidas de ingresos y daño a la reputación.

Este artículo presenta la implementación de una estrategia integral de pruebas para alf.io, una plataforma de código abierto para venta de entradas de eventos. El proyecto implicó diseñar y ejecutar pruebas en cuatro niveles distintos: pruebas unitarias, de integración, de sistema y de aceptación @cohn2004. Cada nivel abordó atributos de calidad específicos y utilizó herramientas y metodologías especializadas para validar diferentes aspectos del comportamiento del sistema.

La implementación de pruebas cubrió toda la pila tecnológica de alf.io, incluyendo el backend Java/Spring Boot @springboot2024, el frontend público Angular y la interfaz de administración basada en Lit. La estrategia incorporó pruebas automatizadas a través de pipelines CI/CD de GitHub Actions @githubactions2024, pruebas de rendimiento con K6 @k6performance2024, fuzzing con Jazzer @jazzer2023 y análisis estático con SonarQube @sonarqube2024. Este enfoque multicapa aseguró cobertura integral de requisitos funcionales y no funcionales.

Los resultados demuestran la efectividad de la estrategia de pruebas implementada, alcanzando tasas de aprobación del 100% en pruebas unitarias, de integración y de aceptación, con una cobertura de código agregada del 85.76% @coverage2015. El proyecto también identificó y documentó defectos, validó contratos de API y estableció procesos de prueba reproducibles a través de pipelines automatizados @cicd2016. Este trabajo proporciona una referencia práctica para implementar estrategias de pruebas integrales en aplicaciones web de código abierto similares @ossquality2007.
